### ISSUE TITLE
PDF and CDF curves need to be smoother

### ISSUE THREAD

**Issue by NattyE** [NattyE/nlstimedist#5]
Currently the PDF uses

    seq(min(data$x), max(data$x), by = max(data$x) / 1000)

as the `xlim` when `xlim` is not user specified. This could possibly be increased beyond 1000 points to make the plot smoother by default. Note: the pdf values are calculated separately using the `tdPDF` function.

The CDF does not specify any limits currently. A separate `tdCDF` function similar to `tdPDF` may be required to calculate the points of the CDF for a sequence of values.

**Comment by NicSteer** [comment]
If allowing the user to manually select a value creates a smoother curve then this would be a great idea.  It may seem trivial but the smoothness of the curves is really important.  I believe that Excel uses a form of Catmull-Rom spline in its smoothing algorithm which uses interpolation to create additional points inbetween the actual data points to make a smoother curve.  I haven't investigated this further as yet though.  Grounding the curves would be great too if a fix is possible?

**Comment by NattyE** [comment]
Well a smart algorithm would be a better idea. If you could have a look into these then that'd be great.

**Comment by NattyE** [comment]
Ok so it turns out that I had already implemented the `xlim` parameter (note I have now changed it to `xVals` so as not to confuse it with the actual `xlim` parameter of `ggplot2`. 

You can pass the `ggtimedistPDF` function a sequence of x-axis values, then for each value of x, `tdPDF` calculates the corresponding y value. Obviously if it only has, say, 5 x-axis values then it will only plot 5 y-axis points so it will not be very smooth. So the default is to create 1000 points which should produce a pretty smooth graph. 

Let me know if you see this behaviour when using the function. Also, double check you have the develop branch installed:

    devtools::install_github("NattyE/nlstimedist", ref = "develop")

**Comment by NattyE** [comment]
So, I decided to rewrite the plot functions a little bit. The plot functions are now known as: `tdPdfPlot` and `tdCdfPlot`. There is also a new `tdCDF` function so the CDF plots should now be much smoother. Let me know how you get on.

**Comment by NicSteer** [comment]
The new tdPdfPlot with the scaling parameters works beautifully.  This was used to produce the graph below:
> tdPdfPlot(lmlobelia1, lmlobelia2, lmlobelia3, lmlobelia4, lmlobelia5, lmlobelia6, lmlobelia7, S = c(0.213, 0.307, 0.533, 0.707, 0.867, 0.907, 0.840), xVals = seq(0, 30, 0.001))

![test tdpdfplot](https://cloud.githubusercontent.com/assets/16936323/17772815/d64893c2-6542-11e6-8686-9b2018db7afd.png)

Unfortunately I could not get the tdCdfPlot to work in the same way for the Lobelia data.  I know the tdCdfPlot function works as I can get the Cactus data to scale using this:

> tdCdfPlot(lmcactus, lmcactus2, lmcactus3, S = c(0.1, 0.5, 0.75), xVals = seq(0, 350, 0.01))

![cactusscaled](https://cloud.githubusercontent.com/assets/16936323/17776583/1d58fe52-6555-11e6-88b9-92237ab5c41b.png)

And for other data using this:

> tdCdfPlot(lmpupae, lmpupae2, lmpupae3, lmpupae4, S = c(0.5, 0.9, 0.8, 0.6), xVals = seq(0, 20, 0.01))

![scaledpupaecdf](https://cloud.githubusercontent.com/assets/16936323/17777329/16497030-6558-11e6-9f34-58cd5b59dfe1.png)

But when I swap out the Cactus/Pupae objects for the first three Lobelia objects using this code:

>tdCdfPlot(lmlobelia1, lmlobelia2, lmlobelia3, S = c(0.1, 0.5, 0.75), xVals = seq(0, 30, 0.01))

It produces this......

![example lobelia cdf](https://cloud.githubusercontent.com/assets/16936323/17776943/7dbdeb26-6556-11e6-929d-4b50c0feb9eb.png)

It looks like the curves would be correct if the y axis was between 0 and 1 but the points still look like they would be off.  In fact the points look like they are being plotted against an x axis of 0 and 1.  Just in case you were wondering the Cactus, Pupae and Lobelia objects were produced in exactly the same way.  I have no explanation for why the y axis would be different for the Lobelia set and not for the others.

Here is the raw Lobelia proportion data and here are the starting values for each one.

[LobeliaProp.xlsx](https://github.com/NattyE/nlstimedist/files/425160/LobeliaProp.xlsx)

> lmlobelia1 <- timedist(lobeliaProp, x = "Day", y = "y9.8", r = 0.1, c = 0.5, t = 25)
lmlobelia2 <- timedist(lobeliaProp, x = "Day", y = "y12.5", r = 0.1, c = 0.5, t = 10)
lmlobelia3 <- timedist(lobeliaProp, x = "Day", y = "y16.7", r = 0.1, c = 0.5, t = 10)
lmlobelia4 <- timedist(lobeliaProp, x = "Day", y = "y20.2", r = 0.1, c = 0.5, t = 10)
lmlobelia5 <- timedist(lobeliaProp, x = "Day", y = "y24.3", r = 0.1, c = 1, t = 5)
lmlobelia6 <- timedist(lobeliaProp, x = "Day", y = "y28.5", r = 0.1, c = 1, t = 5)
lmlobelia7 <- timedist(lobeliaProp, x = "Day", y = "y32.0", r = 0.1, c = 0.5, t = 5)

Would you mind looking in to this please when you get the chance?  Again, if you notice anything obvious please let me know.

**Comment by NattyE** [comment]
I will look into this tonight :)

**Comment by NattyE** [comment]
So this is a kind of strange one. Essentially what is happening is when I extract the data from the model, it is swapping around the x and y columns which what we are seeing in the plot. Unfortunately I use another package to pull out the data.

I have written an additional piece of code which should hopefully fix this (essentially I ensure that the columns are the correct way around); see https://github.com/NattyE/nlstimedist/commit/0725b3b6b19cf4b29828d2474ed1ca77d6864faf for more details.

**Comment by NicSteer** [comment]
Looks pretty good to me!

![lobeliacdf](https://cloud.githubusercontent.com/assets/16936323/17808213/c8b86858-6606-11e6-9989-96b21affea53.png)

**Comment by NattyE** [comment]
Great. I think we can close this issue now.
