### ISSUE TITLE
Scale plot curves to the max number of completions

### ISSUE THREAD

**Issue by NattyE** [NattyE/nlstimedist#6]
Currently all CDF plots go from 0 to 1. Some data points, however, never reach 1 and so we require the plot to be scaled to the maximum number of completions. For example, if only 50% complete, the CDF should be scaled such that it only reaches 0.5.

@NicSteer is this correct? Could you please provide more insight.

**Comment by NicSteer** [comment]
In an ideal world each sample would have the same number but this is not always the case particularly in ecology when you often have to make do with the data you have.  By using the tdPDF function (as above) it is possible to manually scale the curves.  This would be a perfectly acceptable method to use and if a tdCDF function can be made in the same way as the tdPDF this would solve the scaling of the CDFs as well.  It may not be the most elegant of solutions but the ggtimedistCDF/PDF could still be used if no scaling was required.

**Comment by NattyE** [comment]
Ok that's fine. I think the issue is that currently the `tdPDF` function is included within the `ggtimedistPDF` function. So the best option would be to give an option, `S`, in the `ggtimedistPDF` function where you would supply a vector of values - 1 for for each curve.

**Comment by NattyE** [comment]
Ok, I have added an `S` parameter which seems to work as expected. So essentially you can do something like this:

    # Import the data
    cactus <- read.csv("Cactus.csv", header = TRUE)
    
    # Run the models
    lmcactus <- timedist(cactus, x = "x", y = "y1", r = 0.01, c = 0.05, t = 150)
    lmcactus2 <- timedist(cactus, x = "x", y = "y2", r = 0.01, c = 0.05, t = 150)
    
    # Create the plot with no scaling
    ggtimedistPDF(lmcactus, lmcactus2)
    
    # Create the plot with scaling of 0.5
    ggtimedistPDF(lmcactus, lmcactus2, S = c(0.5, 0.5))

Of course you could have any number in the vector `S`. Note that this has to either be the same length as the number of models (i.e. two models needs two scaling values) or have one scaling value only where the same scaling factor will be repeated for all models.

**Comment by NattyE** [comment]
As I mentioned in #5 I have rewritten the plot functions a little. You can now specify values for `S` as mentioned above.

    tdPdfPlot(lmcactus, lmcactus2, S = 0.7, xVals = seq(0, 500, 1))
    tdCdfPlot(lmcactus, lmcactus2, S = 0.7, xVals = seq(0, 500, 1))

**Comment by NattyE** [comment]
This can now be closed
